/* The browser renders server verdicts only. No client-generated K, candidates or scores. */
(()=>{'use strict';
const $=id=>document.getElementById(id),names={basic:'기본 키우기',nutrient:'영양분 발견',retry:'한 번 더'},effects={basic:'자리를 고르고 K를 뽑아요. 가까운 미생물 K마리가 투표해서 색을 정해요.',nutrient:'태어난 색이 1점을 더 받아요! 상대 색이 태어나면 상대가 받아요.',retry:'K를 뽑은 결과가 마음에 안 들면 딱 한 번 더 뽑아요. 자리는 그대로! 두 번째 결과로 정해져요.'},colors={red:'빨강',blue:'파랑'};
let room=null,current=null,layout=[],busy=false,selectedSite=null,selectedCard=null,timer=null,lastError=0;
let polling=false,allowed=false,accessCheck=false,nextCheck=0,accessCode=sessionStorage.getItem('knn-microbe-access')||'';
let fxUntil=0,fxInit=false,fxTimer=null;const fxPlayed=new Set();
const svgNS='http://www.w3.org/2000/svg';
function error(e){if(Date.now()-lastError<1500)return;lastError=Date.now();$('error').textContent=e.message||'연결을 다시 확인해 주세요.';$('error').hidden=false;setTimeout(()=>$('error').hidden=true,5500);}
async function api(type,data={}){await authReady;const token=await fbAuth.currentUser.getIdToken();const response=await fetch('/api/microbe'+(type==='get'?(data.room?'?room='+data.room:''):''),{method:type==='get'?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-Microbe-Access':accessCode},...(type==='get'?{}:{body:JSON.stringify({type,...data})})});const result=await response.json();if(result.code==='HOURS_CLOSED'){allowed=false;nextCheck=result.nextChange;render();}if(!response.ok)throw Object.assign(new Error(result.error||'다시 시도해 주세요.'),{status:response.status});return result;}
function mineTurn(){return current?.status==='playing'&&current.actorIndex===current.me;}
function selecting(){return mineTurn()&&current.game.phase==='choose'&&!busy;}
async function action(type,extra={}){if(busy||!current)return;busy=true;render();try{const result=await api(type,{room,version:current.version,...extra});accept(result);}catch(e){error(e);await poll();}finally{busy=false;render();}}
function accept(v){if(current?.version!==v.version){selectedSite=null;selectedCard=null;}current=v;checkFx();render();}
/* 결과 모션: 새 K 결과(내 것이든 상대 것이든)를 처음 볼 때 한 번 재생한다 */
function fxKey(leg,turn,site,rerolled){return `${leg}-${turn}-${site}-${rerolled?1:0}`;}
function checkFx(){const r=current,g=r?.game;if(!g||!window.MicrobeFX)return;
 if(!fxInit){fxInit=true;if(g.pending&&g.verdict)fxPlayed.add(fxKey(r.leg,g.turn,g.pending.site,g.pending.rerolled));for(const t of g.log)fxPlayed.add(`${r.leg}-${t.turn}`);return;}
 if(g.pending&&g.verdict){const key=fxKey(r.leg,g.turn,g.pending.site,g.pending.rerolled);if(!fxPlayed.has(key)){fxPlayed.add(key);fxPlayed.add(`${r.leg}-${g.turn}`);const site=layout.find(x=>x.id===g.pending.site);startFx({site:g.pending.site,k:g.verdict.k,neighbors:g.verdict.neighbors,color:g.verdict.color,card:g.pending.card.type,rerolled:g.pending.rerolled,points:1+Number(!!site?.nutrient&&g.turn>=7)+Number(g.pending.card.type==='nutrient'),board:g.board});}return;}
 const last=g.log[g.log.length-1];if(last&&!fxPlayed.has(`${r.leg}-${last.turn}`)){fxPlayed.add(`${r.leg}-${last.turn}`);const before={...g.board};delete before[last.site];startFx({...last,board:before});}}
function startFx(v){clearTimeout(fxTimer);draw({board:v.board,pending:v.site,plain:true});const dur=window.MicrobeFX.playVerdict($('board'),layout,v);fxUntil=Date.now()+dur*1000;fxTimer=setTimeout(()=>{fxUntil=0;render();},dur*1000+80);}
async function enter(n){if(busy)return;busy=true;try{const v=await api('join',{room:n});room=n;localStorage.setItem('knn-microbe-room',String(n));accept(v);}catch(e){error(e);}finally{busy=false;render();}}
async function poll(){if(!allowed||document.hidden||polling)return;polling=true;try{if(room){accept(await api('get',{room}));}else{const data=await api('get');$('rooms').replaceChildren();for(const r of data.rooms){const button=document.createElement('button');button.className='room'+(r.mine?' mine':'');button.disabled=!r.mine&&(r.count===2||r.status!=='waiting');const label=r.status==='playing'?'게임 중':r.status==='between'?'2판 준비':r.status==='finished'?'게임 끝':r.count===0?'빈방':r.count===1?'친구 기다리는 중':'게임 준비 중';button.innerHTML=`<strong>${r.id}번 방</strong><span>${r.count}/2명 · ${label}</span><span>${r.mine?'내 자리로 돌아가기':r.count<2&&r.status==='waiting'?'들어가기':'게임 중'}</span>`;button.onclick=()=>enter(r.id);$('rooms').append(button);}$('connection').textContent='방 하나를 골라 주세요';}}catch(e){error(e);if(allowed&&room&&[403,409].includes(e.status)){room=null;current=null;localStorage.removeItem('knn-microbe-room');render();}}finally{polling=false;}}
function shape(tag,attrs,parent=$('board')){const n=document.createElementNS(svgNS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);parent.append(n);return n;}
function label(t,x,y,size,parent,color='#293e51'){const n=shape('text',{x,y,'font-size':size,'text-anchor':'middle',fill:color,'font-family':'sans-serif'},parent);n.textContent=t;return n;}
function microbe(parent,s,color){const x=s.x,y=s.y,fill=color==='red'?'#f29583':'#79bfdc',stroke=color==='red'?'#b74f48':'#347c9d';if(color==='red')shape('circle',{cx:x,cy:y,r:5,fill,stroke,'stroke-width':.6},parent);else shape('polygon',{points:`${x},${y-5.7} ${x-5.4},${y+4.5} ${x+5.4},${y+4.5}`,fill,stroke,'stroke-width':.6},parent);for(const dx of[-1.6,1.6])shape('circle',{cx:x+dx,cy:y,r:.5,fill:'#293e51'},parent);shape('path',{d:`M ${x-1},${y+1.5} Q ${x},${y+3} ${x+1},${y+1.5}`,stroke:'#293e51','stroke-width':.45,fill:'none'},parent);}
function draw(o={}){const svg=$('board');svg.replaceChildren();shape('circle',{cx:148,cy:158,r:108,fill:'#fffdf7',stroke:'#95b5a3','stroke-width':1});const g=current.game,board=o.board||g?.board||Object.fromEntries(layout.filter(s=>s.start).map(s=>[s.id,s.start]));const pending=o.plain?{site:o.pending}:g?.pending,verdict=o.plain?null:g?.verdict;
 if(pending&&verdict){const p=layout.find(s=>s.id===pending.site);for(const id of verdict.neighbors){const n=layout.find(s=>s.id===id);shape('line',{x1:p.x,y1:p.y,x2:n.x,y2:n.y,stroke:'#8660a5','stroke-width':.65,'stroke-dasharray':'2 1'});}}
 for(const s of layout){const candidate=g?.candidates.includes(s.id)&&g.phase==='choose',group=shape('g',{'class':'site'+(candidate?' candidate':'')+(selectedSite===s.id?' selected':''),'data-site':s.id,role:'button',tabindex:candidate&&selecting()?0:-1,'aria-label':`${s.id}번 자리${s.nutrient?' 영양분':''}${board[s.id]?' '+colors[board[s.id]]:candidate?' 고를 수 있는 자리':' 빈자리'}`});
  if(candidate)shape('circle',{cx:s.x,cy:s.y,r:10.4,fill:'#ecdefb',stroke:'#a185c2','stroke-width':.4},group);
  shape('circle',{cx:s.x,cy:s.y,r:7.5,fill:s.nutrient?'#fff0c3':'white',stroke:s.nutrient?'#bc8b30':'#a4b8ab','stroke-width':.6,'class':'socket'},group);
  if(board[s.id])microbe(group,s,board[s.id]);else if(pending?.site===s.id)label('★',s.x,s.y+2.8,9,group,'#7757a0');else if(s.nutrient)label('★',s.x,s.y+2.4,7,group,'#b68a30');
  if(verdict?.neighbors.includes(s.id))shape('circle',{cx:s.x,cy:s.y,r:9,fill:'none',stroke:'#7757a0','stroke-width':1},group);
  label(String(s.id).padStart(2,'0'),s.x,s.y+12,5,group);
  const pick=()=>{if(candidate&&selecting()){selectedSite=s.id;render();}};group.onclick=pick;group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();}};
 }
}
function render(){$('hours-gate').hidden=allowed;const active=allowed&&!!room&&!!current;$('lobby').hidden=!allowed||active;$('match').hidden=!active;if(!active)return;const r=current,g=r.game;const me=r.me,other=1-me;const fx=Date.now()<fxUntil;
 $('room-label').textContent=`${room}번 실험실 · ${r.seats.filter(Boolean).length}/2명`;
 $('scores').replaceChildren();for(let i=0;i<2;i++){const color=r.redIndex===null?'':i===r.redIndex?'red':'blue';const box=document.createElement('div');box.className='score '+color+(r.status==='playing'&&r.actorIndex===i?' active':'');box.innerHTML=`${i===me?'나':'상대'} ${color?'· '+colors[color]:''}<strong>${r.totals[i]}점</strong>`;$('scores').append(box);}
 const readyMode=['waiting','between','finished'].includes(r.status);$('ready-panel').hidden=!readyMode;$('game-panel').hidden=!g||readyMode;
 let message='두 사람이 들어오면 준비를 눌러 주세요.';
 if(r.status==='waiting')message=r.seats.every(Boolean)?'두 사람 모두 준비하면 시작해요.':'친구가 같은 방에 들어오기를 기다려요.';
 if(r.status==='between')message='1판 끝! 이번엔 색을 바꿔서 2판을 해요. 게임 준비를 눌러요.';
 if(r.status==='finished')message=r.finishReason==='surrender'?(r.winnerIndex===me?'상대가 나가서 게임이 끝났어요. 내가 이겼어요!':'게임을 그만두었어요.'):(r.winnerIndex===null?'비겼어요! 두 판 점수를 더하니 똑같아요.':r.winnerIndex===me?'내가 이겼어요! 두 판 점수를 더한 게 더 높아요.':'아쉽게 졌어요. 다음에 다시 도전해요!');
 if(r.status==='playing')message=mineTurn()?(g.phase==='choose'?'내 차례! 카드 1장과 자리 1곳을 골라요.':'K 결과를 보고 "다음 차례로"를 눌러요.'):'상대 차례예요. 조금만 기다려요.';
 if(r.status==='playing'&&Date.now()-r.seen[other]>30000)message+=' 상대 인터넷이 잠깐 끊긴 것 같아요.';
 if(fx)message='두구두구… 가까운 미생물들이 투표하는 중!';
 $('status').textContent=message;$('ready-title').textContent=r.status==='finished'?'다시 할까요?':r.status==='between'?'2판 준비':'게임 준비';$('ready-note').textContent=r.ready[me]?'나는 준비 완료! 상대를 기다려요.':r.ready[other]?'상대는 준비했어요. 준비되면 눌러 주세요.':'두 사람 다 준비해야 시작해요.';$('ready').disabled=busy||!r.seats.every(Boolean)||r.ready[me];$('ready').textContent=r.ready[me]?'준비 완료':'게임 준비';
 $('round-label').textContent=g?`${r.leg}/2판 · ${g.turn}/12차례`:'게임 준비';$('my-color').textContent=r.redIndex===null?'':`나는 ${me===r.redIndex?'빨강':'파랑'}팀`;
 $('board-hint').textContent=g&&g.phase==='choose'?`보라색 자리 ${g.candidates.join(', ')}번 중에서 골라요. ${g.turn>=7?'지금부터 금색(★) 자리는 2점!':'지금은 금색(★) 자리도 1점이에요.'}`:'보라색 선으로 이어진 미생물이 투표한 이웃이에요.';
 $('cards').replaceChildren();if(g)for(const c of g.cards){const button=document.createElement('button');button.className='card'+(selectedCard===c.id||g.pending?.card.id===c.id?' selected':'');button.disabled=!selecting();button.setAttribute('aria-label',names[c.type]);button.setAttribute('aria-pressed',String(selectedCard===c.id));button.innerHTML=`<img src="img/microbe/${c.type}.svg" alt="${names[c.type]} 카드">`;button.onclick=()=>{selectedCard=c.id;render();};$('cards').append(button);}
 const picked=g?.pending?.card||g?.cards.find(c=>c.id===selectedCard);
 $('card-detail').textContent=picked?`${names[picked.type]} · ${effects[picked.type]}`:'카드를 누르면 사용 방법을 크게 볼 수 있어요.';
 $('candidates').replaceChildren();for(const id of g?.phase==='choose'?g.candidates:[]){const b=document.createElement('button');b.className='secondary'+(selectedSite===id?' chosen':'');b.textContent=`${id}번`;b.disabled=!selecting();b.setAttribute('aria-pressed',String(selectedSite===id));b.onclick=()=>{selectedSite=id;render();};$('candidates').append(b);}
 $('roll').hidden=g?.phase!=='choose';$('roll').disabled=!selecting()||selectedSite===null||!selectedCard;
 $('confirm').hidden=g?.phase!=='reveal';$('confirm').disabled=busy||!mineTurn()||fx;$('reroll').hidden=!(g?.phase==='reveal'&&g.pending?.card.type==='retry'&&!g.pending.rerolled);$('reroll').disabled=busy||!mineTurn()||fx;
 $('verdict').textContent=fx?'':g?.verdict?`K = ${g.verdict.k} · 가까운 이웃 ${g.verdict.neighbors.join(', ')}번이 투표 → ${colors[g.verdict.color]} 미생물이 태어났어요!${g.pending.rerolled?' (한 번 더 뽑은 결과예요. 이걸로 정해져요.)':''}`:'';
 $('history').replaceChildren();for(const t of g?.log||[]){const li=document.createElement('li');li.textContent=`${t.turn}번째 · ${t.site}번 자리 / ${names[t.card]} / K=${t.k}${t.rerolled?' (한 번 더)':''} → ${colors[t.color]} +${t.points}점`;$('history').append(li);}if(!fx)draw();
}
async function leave(){if(!room)return;try{await api('leave',{room});room=null;current=null;localStorage.removeItem('knn-microbe-room');render();await poll();}catch(e){error(e);}}
$('ready').onclick=()=>action('ready');$('roll').onclick=()=>action('choose',{site:selectedSite,cardId:selectedCard});$('reroll').onclick=()=>action('reroll');$('confirm').onclick=()=>action('confirm');$('leave').onclick=()=>{if(['playing','between'].includes(current?.status))$('leave-dialog').showModal();else leave();};$('stay').onclick=()=>$('leave-dialog').close();$('leave-confirm').onclick=()=>{$('leave-dialog').close();leave();};
async function checkAccess(){if(accessCheck)return;accessCheck=true;try{const r=await fetch('/api/microbe?access=1',{headers:{'X-Microbe-Access':accessCode}});if(!r.ok)throw new Error('이용 시간을 확인하지 못했어요. 잠시 후 다시 시도해 주세요.');const v=await r.json();allowed=v.allowed;nextCheck=v.override?Infinity:v.nextChange;render();return allowed;}finally{accessCheck=false;}}
$('unlock-form').onsubmit=async e=>{e.preventDefault();accessCode=$('access-code').value;try{if(await checkAccess()){sessionStorage.setItem('knn-microbe-access',accessCode);$('access-code').value='';$('unlock-error').textContent='';await poll();}else{$('unlock-error').textContent='입장 코드를 다시 확인해 주세요.';accessCode='';sessionStorage.removeItem('knn-microbe-access');}}catch(e){$('unlock-error').textContent=e.message;}};
(async()=>{try{layout=(await (await fetch('js/microbe-layout.json')).json()).sites;await checkAccess();await authReady;const saved=Number(localStorage.getItem('knn-microbe-room'));if(allowed&&saved>=1&&saved<=15){try{const v=await api('get',{room:saved});room=saved;accept(v);}catch{localStorage.removeItem('knn-microbe-room');}}await poll();timer=setInterval(async()=>{if(busy||document.hidden)return;try{if(Date.now()>=nextCheck)await checkAccess();if(allowed)await poll();}catch(e){error(e);nextCheck=Date.now()+60000;}},5000);}catch(e){error(e);$('connection').textContent='새로고침해서 다시 들어와 주세요.';}})();
})();
